//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprunter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emprunter()
        {
            this.Degats = new HashSet<Degat>();
        }
    
        public int idEmp { get; set; }
        public Nullable<int> idClt { get; set; }
        public Nullable<int> idmat { get; set; }
        public Nullable<System.DateTime> dateEmprunt { get; set; }
        public Nullable<System.DateTime> dateRetour { get; set; }
        public Nullable<int> dureeEmprunt { get; set; }
        public Nullable<decimal> montantTotal { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Degat> Degats { get; set; }
        public virtual Materiel Materiel { get; set; }
    }
}
